name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Node Setup
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: npm install, build
      run: |
        rm package-lock.json
        npm install
        npm run package

    - name: test
      run: |
        sudo apt-get install xvfb
        xvfb-run --auto-servernum npm test
