name: Build release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      
      - id: changelog
        name: Check changelog
        run: |
          ./.github/workflows/checkChangeLog.sh
          changes=$(./.github/workflows/getChanges.sh)
          echo "Changes:"
          echo $changes
          echo "::set-output name=changes::$changes"

      - id: project-version
        name: Get project version
        run: |
          version=$(./.github/workflows/getVersion.sh)
          suffix=b${{ github.run_number }}
          echo "::set-output name=version::$version"
          echo "::set-output name=release::$version-$suffix"

      - name: Build ${{ steps.project-version.outputs.release }}
        run: |
          rm package-lock.json
          npm install
          npm run package
    
      - name: Test
        run: |
          sudo apt-get install xvfb
          xvfb-run --auto-servernum npm test

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.project-version.outputs.release}}
          release_name: ${{steps.project-version.outputs.release}}
          body: |
            Changes in this Release
            ${{ steps.changelog.outputs.changes }}

          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./vscode-markdown-table-${{steps.project-version.outputs.version}}.vsix
          asset_name: vscode-markdown-table-${{steps.project-version.outputs.version}}.vsix
          asset_content_type: application/vsix

      - uses: lannonbr/vsce-action@3.0.0
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
